# Generated by Django 3.1.5 on 2021-02-05 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_gusto', '0006_usermassages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMassages',
            new_name='UserMessages',
        ),
        migrations.RenameField(
            model_name='usermessages',
            old_name='massge',
            new_name='message',
        ),
    ]
